import { useLanguage } from './i18n'
import { availableBy, isValidDate } from './availability'
import { useState } from 'react'
import { Search, SlidersHorizontal, MapPin, Heart, BedDouble, Bath, Ruler, Camera, ArrowUpRight, X, LayoutGrid, List, ChevronDown } from 'lucide-react'
import { categories } from './data'
import { Link, money, Period, ButtonLink } from './shared'
import './properties.css'

export default function Properties({ go, properties, areas, route, saved, toggleSave }) {const {t}=useLanguage();
  const url = new URL(route, location.origin), q = url.searchParams
  const initial = { moveIn:q.get('moveIn')||'', area:q.get('area')||'', type:url.pathname.split('/')[2]||q.get('type')||'', period:q.get('period')==='yearly'?'yearly':'monthly', min:q.get('min')||'', max:q.get('max')||q.get('budget')||'', furnishing:q.get('furnished')||'', sizeMin:q.get('sizeMin')||'', sizeMax:q.get('sizeMax')||'', keyword:q.get('keyword')||'', video:q.get('video')==='true', saved:q.get('saved')==='true', sort:q.get('sort')||'recommended' }
  const [filters, setFilters] = useState(initial), [more, setMore] = useState(false), [view, setView] = useState('grid')
  function reset() { setFilters({moveIn:'',area:'',type:'',period:'monthly',min:'',max:'',furnishing:'',sizeMin:'',sizeMax:'',keyword:'',video:false,saved:false,sort:'recommended'}); go('/properties') }
  const update = (key, value) => setFilters(f=>({...f,[key]:value}))
  const invalid = (filters.moveIn && !isValidDate(filters.moveIn)) || ['min','max','sizeMin','sizeMax'].some(k=>filters[k]!==''&&(!Number.isFinite(Number(filters[k]))||Number(filters[k])<0))||(filters.min&&filters.max&&+filters.min>+filters.max)||(filters.sizeMin&&filters.sizeMax&&+filters.sizeMin>+filters.sizeMax)
  function search(e) { e?.preventDefault(); if(invalid)return; const params=new URLSearchParams(); Object.entries(filters).forEach(([k,v])=>{if(v!==''&&v!==false)params.set(k==='furnishing'?'furnished':k,String(v))}); go('/properties?'+params) }
  const shown = properties.filter(p=>{
    const price=filters.period==='yearly'?p.yearlyPrice:p.price, size=parseFloat(String(p.size).replaceAll(',',''))
    return availableBy(p,filters.moveIn)&&(!filters.area||p.area===filters.area)&&(!filters.type||p.slug===filters.type)&&(!filters.min||price>=+filters.min)&&(!filters.max||price<=+filters.max)&&(!filters.furnishing||String(p.furnished)===filters.furnishing)&&(!filters.sizeMin||size>=+filters.sizeMin)&&(!filters.sizeMax||size<=+filters.sizeMax)&&(!filters.keyword||`${p.name} ${p.location} ${p.reference} ${p.description}`.toLowerCase().includes(filters.keyword.toLowerCase()))&&(!filters.video||p.video)&&(!filters.saved||saved.includes(p.id))
  }).sort((a,b)=>{const price=p=>filters.period==='yearly'?p.yearlyPrice:p.price;return filters.sort==='low'?price(a)-price(b):filters.sort==='high'?price(b)-price(a):filters.sort==='size'?parseFloat(String(b.size).replaceAll(',',''))-parseFloat(String(a.size).replaceAll(',','')):0})
  const chips = [['moveIn',filters.moveIn&&'Move in by '+filters.moveIn],['area',filters.area],['type',categories.find(c=>c.slug===filters.type)?.label],['furnishing',filters.furnishing === 'true' ? 'Furnished' : filters.furnishing === 'false' ? 'Unfurnished' : ''],['min',filters.min&&'From AED '+money(filters.min)],['max',filters.max&&'Up to AED '+money(filters.max)],['sizeMin',filters.sizeMin&&'From '+filters.sizeMin+' sq ft'],['sizeMax',filters.sizeMax&&'Up to '+filters.sizeMax+' sq ft'],['keyword',filters.keyword],['video',filters.video&&'Video tour'],['saved',filters.saved&&'Saved homes']].filter(([,v])=>v)
  return <main className="rental-market">
    <section className="market-search"><form onSubmit={search}><div className="market-filter-row"><div className="rent-label">{t("For rent")}<ChevronDown size={15}/></div><label className="location-filter"><span>{t("Location")}</span><div><MapPin size={18}/><select aria-label={t("Location")} value={filters.area} onChange={e=>update('area',e.target.value)}><option value="">{t("All UAE neighbourhoods")}</option>{t(areas.map(a=><option key={a.id} value={a.name}>{t(a.name)}{t(",")}{t(a.emirate)}</option>))}</select></div></label><label><span>{t("Home type")}</span><select value={filters.type} onChange={e=>update('type',e.target.value)}><option value="">{t("All apartments")}</option>{t(categories.map(c=><option key={c.slug} value={c.slug}>{t(c.label)}</option>))}</select></label><label><span>{t("Min price (AED)")}</span><input type="number" min="0" placeholder={t("No minimum")} value={filters.min} onChange={e=>update('min',e.target.value)}/></label><label><span>{t("Max price (AED)")}</span><input type="number" min="0" placeholder={t("No maximum")} value={filters.max} onChange={e=>update('max',e.target.value)}/></label><label><span>{t("Move-in date")}</span><input type="date" value={filters.moveIn} onChange={e=>update('moveIn',e.target.value)}/></label><button type="button" className={'more-filters '+(more?'active':'')} aria-controls="advanced-property-filters" aria-expanded={more} onClick={()=>setMore(!more)}><SlidersHorizontal size={17}/>{t(" More filters")}</button><button className="btn" disabled={Boolean(invalid)}><Search size={17}/>{t(" Search")}</button></div>
      {t(more&&<div id="advanced-property-filters" className="extra-filters"><label>{t("Minimum size (sq ft)")}<input type="number" min="0" value={filters.sizeMin} onChange={e=>update('sizeMin',e.target.value)} placeholder={t("Any")}/></label><label>{t("Maximum size (sq ft)")}<input type="number" min="0" value={filters.sizeMax} onChange={e=>update('sizeMax',e.target.value)} placeholder={t("Any")}/></label><label>{t("Keyword or reference")}<input value={filters.keyword} onChange={e=>update('keyword',e.target.value)} placeholder={t("Building, feature or reference")}/></label><label className="check-filter"><input type="checkbox" checked={filters.video} onChange={e=>update('video',e.target.checked)}/>{t(" With video tour")}</label><label className="check-filter"><input type="checkbox" checked={filters.saved} onChange={e=>update('saved',e.target.checked)}/>{t(" Saved homes only")}</label></div>)}
      {t(invalid&&<p className="error" role="alert">{t("Enter a valid date and non-negative values. Minimum values must not exceed maximum values.")}</p>)}
      <div className="filter-summary"><div><span className="rent-chip">{t("To rent")}</span>{t(chips.map(([k,v])=><button type="button" key={k} onClick={()=>update(k,typeof filters[k]==='boolean'?false:'')}>{t(v)}<X size={12}/></button>))}</div><button type="button" className="clear-filters" onClick={reset}>{t("Clear filters")}</button></div>
    </form></section>
    <section className="market-content"><div className="market-breadcrumb"><Link to="/" go={go}>{t("Home")}</Link><span>{t("/")}</span><span>{t("Properties for rent")}</span>{t(filters.area&&<><span>{t("/")}</span><span>{t(filters.area)}</span></>)}</div><div className="market-heading"><div><span className="eyebrow">{t("FIND YOUR NEXT ADDRESS")}</span><h1>{t(filters.type?(categories.find(c=>c.slug===filters.type)?.label+' apartments'):'Properties')}{t(" for rent ")}{t(filters.area?'in '+filters.area:'in the UAE')}</h1><p aria-live="polite">{t(shown.length)} {t(shown.length===1?'home':'homes')}{t(" available to explore")}</p>{t(filters.moveIn&&<p>{t("Showing homes available by this date. Unconfirmed availability is excluded.")}</p>)}</div><Period value={filters.period} onChange={v=>update('period',v)}/></div>
      <div className="market-toolbar"><div className="furnishing-tabs">{t([['','All'],['true','Furnished'],['false','Unfurnished']].map(([v,l])=><button key={v} aria-pressed={filters.furnishing===v} className={filters.furnishing===v?'active':''} onClick={()=>update('furnishing',v)}>{t(l)}</button>))}</div><div className="market-sort"><label>{t("Sort:")}<select value={filters.sort} onChange={e=>update('sort',e.target.value)}><option value="recommended">{t("Recommended")}</option><option value="low">{t("Price: low to high")}</option><option value="high">{t("Price: high to low")}</option><option value="size">{t("Largest first")}</option></select></label><div className="view-switch"><button aria-label={t("List view")} aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={18}/></button><button aria-label={t("Grid view")} aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={18}/></button></div></div></div>
      <div className="market-layout"><div>{t(shown.length?<div className={'market-list '+(view==='grid'?'market-grid':'')}>{t(shown.map(p=><article className="rental-result" key={p.id}><div className="result-photo"><Link to={'/property/'+p.id+'?period='+filters.period} go={go}><img src={p.image} alt={t(p.name)} loading="lazy"/></Link><span className="result-badge">{t(p.demo?'Sample listing':p.furnished?'Furnished':'Unfurnished')}</span><span className="result-photos"><Camera size={14}/>{t(p.images.length)}{t(p.video?' · Video':'')}</span><button className="result-heart" aria-label={t((saved.includes(p.id)?'Unsave ':'Save ')+p.name)} aria-pressed={saved.includes(p.id)} onClick={()=>toggleSave(p.id)}><Heart size={18} fill={saved.includes(p.id)?'currentColor':'none'}/></button></div><div className="result-body"><div className="result-price">{t("AED ")}<strong>{t(money(filters.period==='yearly'?p.yearlyPrice:p.price))}</strong><span>{t(" / ")}{t(filters.period==='yearly'?'year':'month')}</span></div><div className="result-kind">{t("Apartment")}<span>{t("·")}{t(p.furnished?'Furnished':'Unfurnished')}</span></div><Link to={'/property/'+p.id+'?period='+filters.period} go={go}><h2>{t(p.name)}</h2></Link><p className="result-location"><MapPin size={15}/>{t(p.location)}</p><div className="result-facts"><span><BedDouble size={17}/>{t(p.category)}</span><span><Bath size={17}/>{t(p.bathrooms || (p.slug==='2-bhk'?2:1))}{t(" bath")}</span><span><Ruler size={17}/>{t(p.size)}</span></div><div className="result-actions"><span>{t(p.reference)}</span><Link className="btn btn-outline" to={'/property/'+p.id+'?period='+filters.period} go={go}>{t("View property")}<ArrowUpRight size={16}/></Link><Link className="btn" to={'/property/'+p.id+'?period='+filters.period+'&enquire=true'} go={go}>{t("Enquire")}</Link></div></div></article>))}</div>:<div className="empty"><Search/><h2>{t("No matching homes")}</h2><p>{t("Adjust your location, price or home preferences to see more options.")}</p><button className="btn" onClick={reset}>{t("Reset filters")}</button></div>)}<p className="sample-note">{t("Sample listings are design previews. Confirm rental terms and availability with our team.")}</p></div><aside className="market-sidebar"><div><span className="eyebrow">{t("A PLACE THAT FITS")}</span><h2>{t("Need help finding a rental?")}</h2><p>{t("Tell us your preferred neighbourhood and budget. We'll help you take the next step.")}</p><ButtonLink to="/contact" go={go}>{t("Talk to our team")}</ButtonLink></div><div><h3>{t("Explore neighbourhoods")}</h3>{t(areas.map(a=><button key={a.id} onClick={()=>update('area',a.name)}><span>{t(a.name)}</span><span>{t(properties.filter(p=>p.area===a.name).length)}<ArrowUpRight size={14}/></span></button>))}</div></aside></div>
    </section>
  </main>
}
