import { ArrowUpRight, ArrowRight, MapPin, BedDouble, Ruler, Bath, Heart, Check, ShieldCheck, KeyRound, Search, CalendarDays, Building2 } from 'lucide-react'
export { initialAreas as areas } from './areas'
export const money = n => new Intl.NumberFormat('en-AE').format(n)
export async function api(url, options = {}) { const r = await fetch('/api' + url, { ...options, headers: { ...(options.body instanceof File ? {} : {'Content-Type':'application/json'}), ...options.headers } }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Something went wrong. Please try again.'); return d }
export function Link({to,go,children,className='',...rest}){return <a href={to} className={className} onClick={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();go(to)}}} {...rest}>{children}</a>}
export function Brand({go}){return <Link to="/" go={go} className="brand"><span className="brand-mark"><Building2/></span><span>bayt<span className="brand-amp"> & </span>brick<small>HOMES. WITH A LITTLE MORE HEART.</small></span></Link>}
export function ButtonLink({to,go,children,light=false}){return <Link className={`btn ${light?'btn-light':''}`} to={to} go={go}>{children}<ArrowUpRight size={17}/></Link>}
export function Period({value,onChange}){return <div className="period" aria-label="Rental period">{['monthly','yearly'].map(p=><button key={p} type="button" className={value===p?'selected':''} aria-pressed={value===p} onClick={()=>onChange(p)}>{p==='monthly'?'Monthly':'Yearly'}</button>)}</div>}
export function SectionTitle({eyebrow,title,copy,to,go,link='Explore all properties'}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>{to&&<Link className="text-link" to={to} go={go}>{link}<ArrowUpRight size={17}/></Link>}</div>}
export function Card({p,go,period='monthly',saved,toggleSave}){return <article className="property-card"><Link to={'/property/'+p.id+'?period='+period} go={go} className="card-image"><img src={p.image} alt={p.name} loading="lazy"/><span className="image-tag">{p.furnished?'Furnished':'Unfurnished'}</span>{p.demo&&<span className="demo-tag">Sample listing</span>}</Link><button className={`heart ${saved?'saved':''}`} aria-label={saved?'Unsave '+p.name:'Save '+p.name} aria-pressed={saved} onClick={()=>toggleSave(p.id)}><Heart size={17} fill={saved?'currentColor':'none'}/></button><div className="card-body"><p className="card-location"><MapPin size={13}/>{p.location}</p><Link to={'/property/'+p.id+'?period='+period} go={go}><h3>{p.name}</h3></Link><div className="card-facts"><span><BedDouble size={15}/>{p.category}</span><span><Bath size={15}/>{p.slug==='2-bhk'?'2':'1'} bath</span><span><Ruler size={15}/>{p.size}</span></div><div className="card-bottom"><span><strong>AED {money(period==='yearly'?p.yearlyPrice:p.price)}</strong><small> / {period==='yearly'?'year':'month'}</small></span><Link className="circle-link" to={'/property/'+p.id+'?period='+period} go={go} aria-label={'View '+p.name}><ArrowUpRight size={19}/></Link></div></div></article>}
export function Steps(){return <section className="section steps-section"><SectionTitle eyebrow="LESS RUNNING AROUND. MORE SETTLING IN." title={<>Your next home, <em>in three simple steps.</em></>}/><div className="steps-grid">{[[Search,'Find your kind of space','Choose your neighbourhood, home type and a rental period that works for you.'],[CalendarDays,'Come on in','Send a viewing request. Share your preferred date and the homes you’d like to see.'],[KeyRound,'Make yourself at home','Confirm the details with our team, agree the terms and start your next chapter.']].map(([Icon,title,copy],i)=><div key={title}><span className="step-top"><span className="step-icon"><Icon/></span><span>0{i+1}</span></span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>}
export function CTA({go}){return <section className="cta"><div><span className="eyebrow">LET’S MAKE YOUR NEXT MOVE A GOOD ONE</span><h2>Your kind of home.<br/><em>Our kind of thing.</em></h2></div><div><p>A question, a shortlist, or just a starting point.<br/>We’re here to help you find your place.</p><ButtonLink to="/contact" go={go} light>Let’s talk about your next home</ButtonLink></div><span className="cta-arch"/></section>}
