import { useLanguage } from './i18n'
import { ArrowUpRight, ArrowRight, MapPin, BedDouble, Ruler, Bath, Heart, Check, ShieldCheck, KeyRound, Search, CalendarDays, Building2 } from 'lucide-react'
export { initialAreas as areas } from './areas'
export const money = n => new Intl.NumberFormat('en-AE').format(n)
export async function api(url, options = {}) { const r = await fetch('/api' + url, { ...options, headers: { ...(options.body instanceof File ? {} : {'Content-Type':'application/json'}), ...options.headers } }); const d = await r.json(); if (!r.ok) { if (r.status === 401) window.dispatchEvent(new Event('bb-session-expired')); throw new Error(d.error || 'Something went wrong. Please try again.'); } return d }
export function Link({to,go,children,className='',...rest}){const {t}=useLanguage();return <a href={to} className={className} onClick={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();go(to)}}} {...rest}>{t(children)}</a>}
export function Brand({go}){const {t}=useLanguage();return <Link to="/" go={go} className="brand"><span className="brand-mark"><Building2/></span><span>{t("Holidayzone")}<small>{t("APARTMENTS & RENTALS | UAE")}</small></span></Link>}
export function ButtonLink({to,go,children,light=false}){const {t}=useLanguage();return <Link className={`btn ${light?'btn-light':''}`} to={to} go={go}>{t(children)}<ArrowUpRight size={17}/></Link>}
export function Period({value,onChange}){const {t}=useLanguage();return <div className="period" aria-label={t("Rental period")}>{t(['monthly','yearly'].map(p=><button key={p} type="button" className={value===p?'selected':''} aria-pressed={value===p} onClick={()=>onChange(p)}>{t(p==='monthly'?'Monthly':'Yearly')}</button>))}</div>}
export function SectionTitle({eyebrow,title,copy,to,go,link='Explore all properties'}){const {t}=useLanguage();return <div className="section-title"><div><span className="eyebrow">{t(eyebrow)}</span><h2>{t(title)}</h2>{t(copy&&<p>{t(copy)}</p>)}</div>{t(to&&<Link className="text-link" to={to} go={go}>{t(link)}<ArrowUpRight size={17}/></Link>)}</div>}
export function Card({p,go,period='monthly',saved,toggleSave}){const {t}=useLanguage();return <article className="property-card"><Link to={'/property/'+p.id+'?period='+period} go={go} className="card-image"><img src={p.image} alt={t(p.name)} loading="lazy"/><span className="image-tag">{t(p.furnished?'Furnished':'Unfurnished')}</span>{t(p.demo&&<span className="demo-tag">{t("Sample listing")}</span>)}</Link><button className={`heart ${saved?'saved':''}`} aria-label={t(saved?'Unsave '+p.name:'Save '+p.name)} aria-pressed={saved} onClick={()=>toggleSave(p.id)}><Heart size={17} fill={saved?'currentColor':'none'}/></button><div className="card-body"><p className="card-location"><MapPin size={13}/>{t(p.location)}</p><Link to={'/property/'+p.id+'?period='+period} go={go}><h3>{t(p.name)}</h3></Link><div className="card-facts"><span><BedDouble size={15}/>{t(p.category)}</span><span><Bath size={15}/>{t(p.bathrooms || (p.slug==='2-bhk'?2:1))}{t(" bath")}</span><span><Ruler size={15}/>{t(p.size)}</span></div><div className="card-bottom"><span><strong>{t("AED ")}{t(money(period==='yearly'?p.yearlyPrice:p.price))}</strong><small>{t(" / ")}{t(period==='yearly'?'year':'month')}</small></span><Link className="circle-link" to={'/property/'+p.id+'?period='+period} go={go} aria-label={t('View '+p.name)}><ArrowUpRight size={19}/></Link></div><div className="card-contact"><a href="tel:+971543592223">{t("054 359 2223")}</a><Link to={'/property/'+p.id+'?period='+period+'&enquire=true'} go={go}>{t("Request a viewing")}<ArrowRight size={15}/></Link></div></div></article>}
export function Steps(){const {t}=useLanguage();return <section className="section steps-section"><SectionTitle eyebrow="LESS RUNNING AROUND. MORE SETTLING IN." title={t(<>{t("Your next home,")}<em>{t("in three simple steps.")}</em></>)}/><div className="steps-grid">{t([[Search,'Find your kind of space','Choose your neighbourhood, home type and a rental period that works for you.'],[CalendarDays,'Come on in','Send a viewing request. Share your preferred date and the homes you’d like to see.'],[KeyRound,'Make yourself at home','Confirm the details with our team, agree the terms and start your next chapter.']].map(([Icon,title,copy],i)=><div key={title}><span className="step-top"><span className="step-icon"><Icon/></span><span>{t("0")}{t(i+1)}</span></span><h3>{t(title)}</h3><p>{t(copy)}</p></div>))}</div></section>}
export function CTA({go}){const {t}=useLanguage();return <section className="cta"><div><span className="eyebrow">{t("LET’S MAKE YOUR NEXT MOVE A GOOD ONE")}</span><h2>{t("Your kind of home.")}<br/><em>{t("Our kind of thing.")}</em></h2></div><div><p>{t("A question, a shortlist, or just a starting point.")}<br/>{t("We’re here to help you find your place.")}</p><ButtonLink to="/contact" go={go} light>{t("Let’s talk about your next home")}</ButtonLink></div><span className="cta-arch"/></section>}
