import { useLanguage, LanguageSelector } from './i18n'
import Assistant from './Assistant'
import {useEffect,useState} from 'react'
import {MapPin,Menu,X,ArrowUpRight,LoaderCircle,ChevronDown} from 'lucide-react'
import {categories} from './data'
import {api,Brand,Link,ButtonLink} from './shared'
import Home from './Landing'
import {Properties,Detail,Areas,About,Contact} from './Pages'
import Admin from './Admin'
function useRoute(){const [route,setRoute]=useState(location.pathname+location.search);useEffect(()=>{const fn=()=>setRoute(location.pathname+location.search);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);function go(to){history.pushState({},'',to);setRoute(to);window.scrollTo({top:0,behavior:'instant'})}return [route,go]}
function Header({go,path}) {const {t}=useLanguage();
  const [open,setOpen]=useState(false),[propertiesOpen,setPropertiesOpen]=useState(false),[scrolled,setScrolled]=useState(window.scrollY>36)
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>36);addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[])
  const navigate=to=>{setOpen(false);setPropertiesOpen(false);go(to)}
  return <header className={['site-header',path==='/'?'home-header':'',scrolled?'is-scrolled':'',open?'menu-is-open':''].join(' ')}><div className="header-inner"><Brand go={navigate}/><LanguageSelector/><button className="mobile-menu" aria-label={t("Toggle menu")} aria-expanded={open} onClick={()=>setOpen(!open)}>{t(open?<X/>:<Menu/>)}</button><nav className={open?'open':''} aria-label={t("Main navigation")}><Link to="/" go={navigate} className={path==='/'?'active':''}>{t("Home")}</Link><div className="nav-property-group" onMouseLeave={()=>setPropertiesOpen(false)}><div><Link to="/properties" go={navigate} className={path.startsWith('/propert')?'active':''}>{t("Properties")}</Link><button className="nav-dropdown-toggle" aria-label={t("Show property types")} aria-expanded={propertiesOpen} onClick={()=>setPropertiesOpen(!propertiesOpen)}><ChevronDown size={14}/></button></div>{t(propertiesOpen&&<div className="nav-property-dropdown">{t(categories.map(c=><Link key={c.slug} to={'/properties/'+c.slug} go={navigate}><span>{t(c.label)}{t(" apartments")}</span><ArrowUpRight size={15}/></Link>))}<Link to="/properties?period=monthly" go={navigate}>{t("Monthly rentals")}</Link><Link to="/properties?period=yearly" go={navigate}>{t("Yearly rentals")}</Link></div>)}</div><Link to="/areas" go={navigate} className={path==='/areas'?'active':''}>{t("Neighbourhoods")}</Link><Link to="/about" go={navigate} className={path==='/about'?'active':''}>{t("About us")}</Link><Link to="/contact" go={navigate} className={path==='/contact'?'active':''}>{t("Contact")}</Link><Link to="/properties?saved=true" go={navigate}>{t("Saved homes")}</Link><ButtonLink to="/contact" go={navigate}>{t("Find a rental")}</ButtonLink></nav></div></header>
}
function Footer({go}){const {t}=useLanguage();return <footer className="rental-footer"><div className="footer-main"><div><Brand go={go}/><p>{t("Find studios and apartments across the UAE, with monthly and yearly rental options.")}</p><span className="footer-location"><MapPin size={14}/>{t(" United Arab Emirates")}</span></div><div><h3>{t("Browse rentals")}</h3><div className="footer-types">{t(categories.map(c=><Link key={c.slug} to={'/properties/'+c.slug} go={go}>{t(c.label)}{t(" apartments")}</Link>))}</div></div><div><h3>{t("Rental resources")}</h3><Link to="/properties?saved=true" go={go}>{t("Your saved homes")}</Link><Link to="/areas" go={go}>{t("Explore neighbourhoods")}</Link><Link to="/about" go={go}>{t("About Holidayzone")}</Link><Link to="/contact" go={go}>{t("Request a viewing")}</Link><Link to="/admin" go={go}>{t("Team sign in")}</Link></div><div className="footer-contact"><h3>{t("Speak to our team")}</h3><p>{t("Questions about a listing? Have its reference ready when you contact us.")}</p><a href="tel:+971543592223">{t("Call 054 359 2223")}<ArrowUpRight size={16}/></a><a href="https://wa.me/971509794499" target="_blank" rel="noreferrer">{t("WhatsApp 050 979 4499")}<ArrowUpRight size={16}/></a></div></div><div className="footer-bottom"><span>{t("©")}{t(new Date().getFullYear())}{t(" Holidayzone. All rights reserved.")}</span><span>{t("Developed by Kairlix Tech | Naimat Khan")}</span></div></footer>}
export default function Site(){const {t}=useLanguage();const [route,go]=useRoute(),[properties,setProperties]=useState([]),[areas,setAreas]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState(()=>{try{const s=JSON.parse(localStorage.getItem('bb-saved')||'[]');return Array.isArray(s)?s:[]}catch{return []}});async function reload(){const [d,a]=await Promise.all([api('/properties'),api('/areas')]);setProperties(d);setAreas(a);setError('')}useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const path=route.split('?')[0],toggleSave=id=>setSaved(s=>{const next=s.includes(id)?s.filter(x=>x!==id):[...s,id];try{localStorage.setItem('bb-saved',JSON.stringify(next))}catch{}return next});useEffect(()=>{document.title=t(path==='/'?'Apartments for rent in the UAE':path==='/admin'?'Admin dashboard':path==='/about'?'Our story':path==='/areas'?'UAE neighbourhoods':path==='/contact'?'Find your home':'UAE rental properties')+' | Holidayzone'},[path,t]);let page;const common={go,properties,areas,saved,toggleSave};if(path==='/admin')page=<div dir="ltr" lang="en"><Admin properties={properties} areas={areas} reload={reload}/></div>;else if(loading)page=<div className="loading"><LoaderCircle/><p>{t("Opening the door to your next home…")}</p></div>;else if(error)page=<div className="empty"><h1>{t("We couldn’t load the homes.")}</h1><p>{t(error)}</p><button className="btn" onClick={()=>{setLoading(true);reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))}}>{t("Try again")}</button></div>;else if(path==='/')page=<Home {...common}/>;else if(path==='/properties'||/^\/properties\/(studio|[1-8]-bhk)$/.test(path))page=<Properties key={route} {...common} route={route}/>;else if(categories.some(c=>path==='/'+c.slug))page=<Properties key={route} {...common} route={'/properties'+route}/>;else if(path.startsWith('/property/')||/^\/(studio|[1-8]-bhk)\/.+/.test(path)){const p=properties.find(p=>p.id===path.split('/').pop());page=p?<Detail key={p.id} {...common} p={p} route={route}/>:null}else if(path==='/areas')page=<Areas {...common}/>;else if(path==='/about')page=<About {...common}/>;else if(path==='/contact')page=<Contact/>;return <><a href="#main-content" className="skip-link">{t("Skip to content")}</a><Header go={go} path={path}/><div id="main-content">{t(page||<div className="empty"><span className="eyebrow">{t("404 · A LITTLE OFF THE MAP")}</span><h1>{t("Let’s get you")}<em>{t("home.")}</em></h1><ButtonLink to="/" go={go}>{t("Back to home")}</ButtonLink></div>)}</div><Footer go={go}/>{t(path!=='/admin'&&<Assistant properties={properties} areas={areas} go={go}/>)}</>}
