import {useEffect,useState} from 'react'
import {MapPin,Menu,X,ArrowUpRight,LoaderCircle,ChevronDown} from 'lucide-react'
import {categories} from './data'
import {api,Brand,Link,ButtonLink} from './shared'
import Home from './Landing'
import {Properties,Detail,Areas,About,Contact} from './Pages'
import Admin from './Admin'
function useRoute(){const [route,setRoute]=useState(location.pathname+location.search);useEffect(()=>{const fn=()=>setRoute(location.pathname+location.search);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);function go(to){history.pushState({},'',to);setRoute(to);window.scrollTo({top:0,behavior:'instant'})}return [route,go]}
function Header({go,path}) {
  const [open,setOpen]=useState(false),[propertiesOpen,setPropertiesOpen]=useState(false),[scrolled,setScrolled]=useState(window.scrollY>36)
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>36);addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[])
  const navigate=to=>{setOpen(false);setPropertiesOpen(false);go(to)}
  return <header className={['site-header',path==='/'?'home-header':'',scrolled?'is-scrolled':'',open?'menu-is-open':''].join(' ')}><div className="header-inner"><Brand go={navigate}/><button className="mobile-menu" aria-label="Toggle menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} aria-label="Main navigation"><Link to="/" go={navigate} className={path==='/'?'active':''}>Home</Link><div className="nav-property-group" onMouseLeave={()=>setPropertiesOpen(false)}><div><Link to="/properties" go={navigate} className={path.startsWith('/propert')?'active':''}>Properties</Link><button className="nav-dropdown-toggle" aria-label="Show property types" aria-expanded={propertiesOpen} onClick={()=>setPropertiesOpen(!propertiesOpen)}><ChevronDown size={14}/></button></div>{propertiesOpen&&<div className="nav-property-dropdown">{categories.map(c=><Link key={c.slug} to={'/properties/'+c.slug} go={navigate}><span>{c.label} apartments</span><ArrowUpRight size={15}/></Link>)}<Link to="/properties?period=monthly" go={navigate}>Monthly rentals</Link><Link to="/properties?period=yearly" go={navigate}>Yearly rentals</Link></div>}</div><Link to="/areas" go={navigate} className={path==='/areas'?'active':''}>Neighbourhoods</Link><Link to="/about" go={navigate} className={path==='/about'?'active':''}>About us</Link><Link to="/contact" go={navigate} className={path==='/contact'?'active':''}>Contact</Link><ButtonLink to="/contact" go={navigate}>Find your home</ButtonLink></nav></div></header>
}
function Footer({go}){return <footer><div className="footer-main"><div><Brand go={go}/><p>A considered space. A fresh beginning.<br/>Find a little more home in the UAE.</p><span className="footer-location"><MapPin size={13}/> United Arab Emirates</span></div><div><h3>Find your home</h3>{categories.map(c=><Link key={c.slug} to={'/properties/'+c.slug} go={go}>{c.label} apartments</Link>)}<Link to="/properties?period=yearly" go={go}>Yearly rentals</Link></div><div><h3>A little more</h3><Link to="/about" go={go}>Our story</Link><Link to="/areas" go={go}>Neighbourhoods</Link><Link to="/contact" go={go}>Get in touch</Link><Link to="/admin" go={go}>Admin sign in</Link></div><div className="footer-note"><span>LET’S FIND YOUR PLACE.</span><h3>Good spaces.<br/><em>Better beginnings.</em></h3><Link to="/contact" go={go} className="text-link">Start a conversation <ArrowUpRight size={17}/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Bayt & Brick. All rights reserved.</span><span>Developed by Kairlix Tech | Naimat Khan</span></div></footer>}
export default function Site(){const [route,go]=useRoute(),[properties,setProperties]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState(()=>{try{const s=JSON.parse(localStorage.getItem('bb-saved')||'[]');return Array.isArray(s)?s:[]}catch{return []}});async function reload(){const d=await api('/properties');setProperties(d);setError('')}useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const path=route.split('?')[0],toggleSave=id=>setSaved(s=>{const next=s.includes(id)?s.filter(x=>x!==id):[...s,id];try{localStorage.setItem('bb-saved',JSON.stringify(next))}catch{}return next});useEffect(()=>{document.title=(path==='/'?'Homes with a little more heart':path==='/admin'?'Admin dashboard':path==='/about'?'Our story':path==='/areas'?'UAE neighbourhoods':path==='/contact'?'Find your home':'UAE rental properties')+' | Bayt & Brick'},[path]);let page;const common={go,properties,saved,toggleSave};if(path==='/admin')page=<Admin properties={properties} reload={reload}/>;else if(loading)page=<div className="loading"><LoaderCircle/><p>Opening the door to your next home…</p></div>;else if(error)page=<div className="empty"><h1>We couldn’t load the homes.</h1><p>{error}</p><button className="btn" onClick={()=>{setLoading(true);reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))}}>Try again</button></div>;else if(path==='/')page=<Home {...common}/>;else if(path==='/properties'||/^\/properties\/(studio|1-bhk|2-bhk)$/.test(path))page=<Properties key={route} {...common} route={route}/>;else if(['/studio','/1-bhk','/2-bhk'].includes(path))page=<Properties key={route} {...common} route={'/properties'+route}/>;else if(path.startsWith('/property/')||/^\/(studio|1-bhk|2-bhk)\/.+/.test(path)){const p=properties.find(p=>p.id===path.split('/').pop());page=p?<Detail key={p.id} {...common} p={p} route={route}/>:null}else if(path==='/areas')page=<Areas {...common}/>;else if(path==='/about')page=<About go={go}/>;else if(path==='/contact')page=<Contact/>;return <><a href="#main-content" className="skip-link">Skip to content</a><Header go={go} path={path}/><div id="main-content">{page||<div className="empty"><span className="eyebrow">404 · A LITTLE OFF THE MAP</span><h1>Let’s get you <em>home.</em></h1><ButtonLink to="/" go={go}>Back to home</ButtonLink></div>}</div>{path!=='/admin'&&path!=='/contact'&&<Link className="contact-rail" to="/contact" go={go}>GET IN TOUCH <ArrowUpRight size={17}/></Link>}<Footer go={go}/></>}
