import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import assert from 'node:assert/strict'
const root = process.cwd(), tmp = await fs.mkdtemp(path.join(os.tmpdir(),'bb-ui-test-'))
let child, browser, page
try {
  await fs.cp(path.join(root,'dist'),path.join(tmp,'dist'),{recursive:true})
  child = spawn(process.execPath,[path.join(root,'server.mjs')],{cwd:tmp,env:{...process.env,PORT:'0',HOST:'127.0.0.1',ADMIN_USERNAME:'qa-owner',ADMIN_PASSWORD:'QaOwnerPassword!42',NODE_ENV:'test'},stdio:['ignore','pipe','pipe']})
  const origin = await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout')),10000);child.stdout.once('data',data=>{clearTimeout(timer);resolve(data.toString().trim().match(/http:\/\/[^ ]+/)[0].replace('localhost','127.0.0.1'))});child.once('error',reject)})
  browser = await chromium.launch({channel:'msedge',headless:true})
  page = await browser.newPage({viewport:{width:1440,height:1000}}); const errors=[]
  page.setDefaultTimeout(20000)
  page.on('pageerror',error=>{errors.push(error.message);console.log('Page error:',error.message)})

  await page.route('https://**/*',route=>route.abort())
  await page.goto(origin+'/admin',{waitUntil:'domcontentloaded'})
  await page.getByLabel('Username',{exact:true}).fill('qa-owner')
  await page.getByLabel('Password',{exact:true}).fill('QaOwnerPassword!42')
  await page.getByRole('button',{name:'Sign in securely'}).click()
  await page.getByRole('button',{name:'Roles',exact:true}).click()
  await page.getByRole('button',{name:'Create role',exact:true}).click()
  await page.getByLabel('Role name',{exact:true}).fill('UI Editor')
  await page.getByLabel('Add properties and upload media',{exact:true}).check()
  await page.getByRole('button',{name:'Save role',exact:true}).click()
  await page.getByText('Role saved.',{exact:false}).waitFor()
  await page.getByRole('button',{name:'Users',exact:true}).click()
  await page.getByRole('button',{name:'Add user',exact:true}).click()
  await page.getByLabel('Full name',{exact:true}).fill('UI Test Editor')
  await page.getByLabel('Username',{exact:true}).fill('ui-editor')
  await page.getByLabel('Password',{exact:true}).fill('UiEditorPassword!42')
  await page.getByLabel('Role',{exact:true}).selectOption({label:'UI Editor'})
  await page.getByRole('button',{name:'Save user',exact:true}).click()
  await page.getByText('User saved.',{exact:false}).waitFor()
  await page.screenshot({path:'qa/team-desktop.png'})
  console.log('Role creation and user creation passed')
  await page.getByRole('button',{name:'Add property',exact:true}).click()
  await page.getByLabel('Property title',{exact:true}).fill('UI eight bedroom home')
  await page.getByLabel('Size (sq ft)',{exact:true}).fill('4000')
  await page.getByLabel('Monthly rent (AED)',{exact:true}).fill('10000')
  await page.getByLabel('Yearly rent (AED)',{exact:true}).fill('110000')
  await page.getByLabel('Home type',{exact:true}).selectOption('8-bhk')
  await page.getByLabel('Available from',{exact:false}).fill('2026-10-01')
  await page.getByLabel('Bathrooms',{exact:true}).fill('5')
  await page.locator('input[type=file]').setInputFiles(path.join(root,'public/assets/studio.webp'))
  await page.getByRole('button',{name:'Save property',exact:true}).waitFor()
  await page.getByRole('button',{name:'Save property',exact:true}).click()
  await page.getByText('Property saved.',{exact:false}).waitFor()
  await page.getByRole('button',{name:'Activity',exact:true}).click()
  await page.getByLabel('Search',{exact:true}).fill('UI eight bedroom home')
  await page.getByText('property: UI eight bedroom home',{exact:true}).waitFor()
  await page.getByText('View recorded changes',{exact:true}).click()
  await page.getByRole('cell',{name:'8-bhk',exact:true}).waitFor()
  console.log('8 BHK property upload, date and audit details passed')
  await page.goto(origin+'/',{waitUntil:'domcontentloaded'})
  await page.getByLabel('Choose property type',{exact:true}).selectOption('8-bhk')
  await page.getByLabel('Move-in date',{exact:true}).fill('2026-10-01')
  await page.getByRole('button',{name:'Find my home'}).click()
  await page.getByRole('heading',{name:'UI eight bedroom home',exact:true}).waitFor()
  assert(page.url().includes('moveIn=2026-10-01'))
  await page.getByLabel('Move-in date',{exact:true}).fill('2026-09-30')
  await page.getByRole('heading',{name:'No matching homes',exact:true}).waitFor()
  console.log('Homepage date forwarding and catalogue date filtering passed')
  await page.setViewportSize({width:390,height:844})
  await page.goto(origin+'/',{waitUntil:'domcontentloaded'})
  await page.getByLabel('Move-in date',{exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile homepage must not overflow')
  await page.screenshot({path:'qa/date-mobile.png',fullPage:false})
  await page.goto(origin+'/admin',{waitUntil:'domcontentloaded'})
  await page.getByRole('button',{name:'Users',exact:true}).click()
  await page.getByText('UI Test Editor',{exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile admin must not overflow')
  await page.screenshot({path:'qa/team-mobile.png'})
  await page.getByRole('button',{name:'Sign out',exact:true}).click()
  await page.getByLabel('Username',{exact:true}).fill('ui-editor')
  await page.getByLabel('Password',{exact:true}).fill('UiEditorPassword!42')
  await page.getByRole('button',{name:'Sign in securely'}).click()
  await page.getByRole('button',{name:'Add property',exact:true}).waitFor()
  assert.equal(await page.getByRole('button',{name:'Users',exact:true}).count(),0)
  assert.equal(await page.getByRole('button',{name:'Edit',exact:true}).count(),0)
  assert.equal(await page.getByRole('button',{name:/^Delete /}).count(),0)
  assert.deepEqual(errors,[])
  console.log('Mobile layout and restricted user navigation passed; no page errors')
} catch(error) { console.error('Browser failure URL:',page?.url()); if(page){console.error((await page.locator('body').innerText()).slice(0,3000));await page.screenshot({path:'qa/access-failure.png'})}; throw error } finally {
  await browser?.close()
  if(child?.exitCode===null){const done=new Promise(resolve=>child.once('exit',resolve));child.kill();await done}
  assert(tmp.startsWith(path.join(os.tmpdir(),'bb-ui-test-')));await fs.rm(tmp,{recursive:true,force:true})
}
