import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { promises as fs } from 'node:fs'
const browser = await chromium.launch({headless:true,channel:'chrome'})
const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'})
const errors=[];page.on('pageerror',e=>errors.push(e.message))
const base='http://127.0.0.1:3001'
async function loadImages(){await page.locator('img').evaluateAll(async imgs=>{for(const img of imgs){img.loading='eager'}await Promise.all(imgs.map(img=>img.decode().catch(()=>{})))})}
try{
  await page.goto(base);await page.getByRole('heading',{name:'Find your place. Live your way.'}).waitFor();await loadImages();assert(await page.locator('.destination-copy').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.destination-search').getBoundingClientRect().top),'Search must not overlap hero copy');await page.screenshot({path:'qa/home-desktop.png',fullPage:true});await page.screenshot({path:'qa/desktop-fold.png'});
  await page.getByRole('button',{name:'Next featured image'}).click();assert.match(await page.locator('.slide-caption').innerText(),/more room/);await page.getByRole('button',{name:'Previous featured image'}).click();assert.match(await page.locator('.slide-caption').innerText(),/fresh perspective/);
  await page.getByRole('button',{name:'Show property types'}).click();await page.locator('.nav-property-dropdown').getByRole('link',{name:'2 BHK apartments'}).click();await page.getByRole('heading',{name:'2 BHK apartments to call home.'}).waitFor();await page.getByRole('navigation').getByRole('link',{name:'Home',exact:true}).click();await page.getByRole('heading',{name:'Find your place. Live your way.'}).waitFor();
  await page.locator('summary').filter({hasText:'Can I rent monthly or yearly?'}).click();assert(await page.locator('details').first().getAttribute('open')!==null);
  await page.getByRole('combobox',{name:'Choose area'}).selectOption('Al Nahda');await page.getByRole('combobox',{name:'Choose property type'}).selectOption('1-bhk');await page.getByRole('button',{name:'Yearly',exact:true}).click();await page.getByRole('button',{name:'Find my home'}).click();await page.getByRole('heading',{name:'1 BHK apartments to call home.'}).waitFor();assert.equal(await page.locator('.property-card').count(),1);assert.match(await page.locator('.card-bottom').innerText(),/28,800/)
  await page.locator('.heart').click();assert.equal(await page.locator('.heart').getAttribute('aria-pressed'),'true');await page.reload();await page.locator('.property-card').waitFor();assert.equal(await page.locator('.heart').getAttribute('aria-pressed'),'true')
  await page.locator('.card-image').click();await page.getByRole('heading',{name:'Unfurnished 1 BHK near Al Zahia',exact:true}).waitFor();assert.match(await page.locator('.booking-price').innerText(),/28,800/);await page.getByRole('button',{name:'Enlarge property photo'}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0)
  for(const route of ['/properties','/properties/studio','/properties/2-bhk','/about','/areas','/contact','/not-a-page']){await page.goto(base+route);await page.locator('main, .empty').first().waitFor();assert.equal(await page.locator('h1').count(),1)}
  await page.goto(base+'/admin');await page.getByRole('heading',{name:'Welcome back.'}).waitFor();await page.screenshot({path:'qa/admin-login.png'})
  const credentials=await fs.readFile('.local/admin-access.txt','utf8');const password=credentials.match(/Password: (.+)/)[1];await page.getByLabel('Username',{exact:true}).fill(credentials.match(/Username: (.+)/)[1]);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in securely'}).click();await page.getByRole('heading',{name:'Your homes. Your dashboard.'}).waitFor();await page.screenshot({path:'qa/admin-dashboard.png',fullPage:true});await page.getByRole('button',{name:'Add property'}).click();await page.getByLabel('Property title').waitFor();await page.screenshot({path:'qa/admin-editor.png',fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('heading',{name:'Welcome back.'}).waitFor()
  await page.setViewportSize({width:390,height:844});await page.goto(base);await page.getByRole('heading',{name:'Find your place. Live your way.'}).waitFor();await loadImages();await page.screenshot({path:'qa/home-mobile.png',fullPage:true});await page.screenshot({path:'qa/mobile-fold.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'Toggle menu'}).click();await page.getByRole('navigation').getByRole('link',{name:'Properties',exact:true}).click();await page.getByRole('heading',{name:'Find your next place to belong.'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa/properties-mobile.png',fullPage:true})
  for(const route of ['/property/studio-1','/areas','/about','/contact','/admin']){await page.goto(base+route);await page.locator('h1').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflows')}
  assert.deepEqual(errors,[]);console.log('Browser checks passed: desktop/mobile pages, navigation, area/type/yearly filtering, saved homes, gallery, admin login/editor/logout; no page errors or mobile overflow.')
} finally {await browser.close()}


